### ISSUE TITLE
WASI and waPC guest coexistence

### ISSUE THREAD

**Issue by ereslibre** [chimera-kube/policy-server#20]
Consider if it makes sense for the policy-server to detect whether a guest module is WASI or waPC and load one or the other. This has implications on our side at the policy-server, but it virtually enables any kind of language that is able to use either WASI or waPC.

**Comment by kkaempf** [comment]
Didn't we decide for waPC finally ? Can we close this issue ?

**Comment by flavio** [comment]
Yes, I think we can close this issue. The future is with waPC
